# In docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthtech
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: